import type { Question, QuestionBank } from './types';

const questions: Question[] = [
  // ============ 心理能量模式 (6题) ============
  {
    id: 'L1-ENERGY-001',
    type: 'binary',
    level: 'L1',
    dimension: 'energy',
    text: '放学后你有一整个下午的自由时间，你更想：',
    theorySource: 'Jung E-I',
    options: [
      { id: 'L1-ENERGY-001-A', text: '一个人安安静静地做自己喜欢的事', scores: [{ dimension: 'energy', subDimension: 'energy.introversion', value: 2 }] },
      { id: 'L1-ENERGY-001-B', text: '找小伙伴一起玩', scores: [{ dimension: 'energy', subDimension: 'energy.extraversion', value: 2 }] },
    ],
  },
  {
    id: 'L1-ENERGY-002',
    type: 'binary',
    level: 'L1',
    dimension: 'energy',
    text: '周末做了一整天的事，哪种情况你虽然累但很开心？',
    theorySource: 'Flow Theory',
    options: [
      { id: 'L1-ENERGY-002-A', text: '在外面跑了一天，打球/爬山/探险', scores: [{ dimension: 'energy', subDimension: 'energy.physical', value: 2 }] },
      { id: 'L1-ENERGY-002-B', text: '在家研究了一天喜欢的东西（拼乐高/画画/看书/玩游戏）', scores: [{ dimension: 'energy', subDimension: 'energy.flow', value: 2 }] },
    ],
  },
  {
    id: 'L1-ENERGY-003',
    type: 'scenario',
    level: 'L1',
    dimension: 'energy',
    text: '学校要搞一个大活动，你最想负责哪个部分？',
    theorySource: 'Flow Theory + Gardner MI',
    options: [
      { id: 'L1-ENERGY-003-A', text: '设计海报和装饰教室', scores: [{ dimension: 'energy', subDimension: 'energy.creative', value: 3 }] },
      { id: 'L1-ENERGY-003-B', text: '上台主持或表演节目', scores: [{ dimension: 'energy', subDimension: 'energy.social', value: 3 }] },
      { id: 'L1-ENERGY-003-C', text: '帮老师安排流程，确保不出乱子', scores: [{ dimension: 'energy', subDimension: 'energy.order', value: 3 }] },
      { id: 'L1-ENERGY-003-D', text: '想出一个超酷的活动点子', scores: [{ dimension: 'energy', subDimension: 'energy.intellectual', value: 3 }] },
    ],
  },
  {
    id: 'L1-ENERGY-004',
    type: 'binary',
    level: 'L1',
    dimension: 'energy',
    text: '你更喜欢哪种作业？',
    theorySource: 'Jung J-P',
    options: [
      { id: 'L1-ENERGY-004-A', text: '有明确答案的（数学题、填空题）', scores: [{ dimension: 'energy', subDimension: 'energy.certainty', value: 2 }] },
      { id: 'L1-ENERGY-004-B', text: '没有标准答案的（写作文、做手工、做实验）', scores: [{ dimension: 'energy', subDimension: 'energy.ambiguity', value: 2 }] },
    ],
  },
  {
    id: 'L1-ENERGY-005',
    type: 'binary',
    level: 'L1',
    dimension: 'energy',
    text: '如果可以选，你更想：',
    theorySource: 'Gallup Strengths',
    options: [
      { id: 'L1-ENERGY-005-A', text: '学一个全新的、从没接触过的东西', scores: [{ dimension: 'energy', subDimension: 'energy.novelty', value: 2 }] },
      { id: 'L1-ENERGY-005-B', text: '把已经会的东西练到超级厉害', scores: [{ dimension: 'energy', subDimension: 'energy.mastery', value: 2 }] },
    ],
  },
  {
    id: 'L1-ENERGY-006',
    type: 'scenario',
    level: 'L1',
    dimension: 'energy',
    text: '下课十分钟，你通常在干嘛？',
    theorySource: 'Jung E-I + Flow',
    options: [
      { id: 'L1-ENERGY-006-A', text: '和同学聊天、打闹', scores: [{ dimension: 'energy', subDimension: 'energy.social', value: 3 }] },
      { id: 'L1-ENERGY-006-B', text: '看课外书或者发呆想事情', scores: [{ dimension: 'energy', subDimension: 'energy.introversion', value: 3 }] },
      { id: 'L1-ENERGY-006-C', text: '到处转转，去操场活动一下', scores: [{ dimension: 'energy', subDimension: 'energy.physical', value: 3 }] },
      { id: 'L1-ENERGY-006-D', text: '继续研究刚才课上感兴趣的内容', scores: [{ dimension: 'energy', subDimension: 'energy.intellectual', value: 3 }] },
    ],
  },

  // ============ 天然能力图谱 (8题) ============
  {
    id: 'L1-ABILITY-001',
    type: 'scenario',
    level: 'L1',
    dimension: 'intelligence',
    text: '班里来了一个转学生，不太适应。你会怎么做？',
    theorySource: 'Gardner MI',
    options: [
      { id: 'L1-ABILITY-001-A', text: '主动去找他聊天，带他认识大家', scores: [{ dimension: 'intelligence', subDimension: 'intel.interpersonal', value: 3 }] },
      { id: 'L1-ABILITY-001-B', text: '默默观察他，猜猜他是什么样的人', scores: [{ dimension: 'intelligence', subDimension: 'intel.intrapersonal', value: 3 }] },
      { id: 'L1-ABILITY-001-C', text: '不太关注，继续做自己的事', scores: [{ dimension: 'intelligence', subDimension: 'intel.intrapersonal', value: 3 }] },
      { id: 'L1-ABILITY-001-D', text: '画个班级座位图给他，告诉他哪里是什么', scores: [{ dimension: 'intelligence', subDimension: 'intel.spatial', value: 3 }] },
    ],
  },
  {
    id: 'L1-ABILITY-002',
    type: 'binary',
    level: 'L1',
    dimension: 'intelligence',
    text: '你觉得自己哪个更强？',
    theorySource: 'Gardner MI',
    options: [
      { id: 'L1-ABILITY-002-A', text: '说服别人同意我的想法', scores: [{ dimension: 'intelligence', subDimension: 'intel.linguistic', value: 1 }, { dimension: 'intelligence', subDimension: 'intel.interpersonal', value: 1 }] },
      { id: 'L1-ABILITY-002-B', text: '自己安静地想明白一个问题', scores: [{ dimension: 'intelligence', subDimension: 'intel.logicMath', value: 1 }, { dimension: 'intelligence', subDimension: 'intel.intrapersonal', value: 1 }] },
    ],
  },
  {
    id: 'L1-ABILITY-003',
    type: 'scenario',
    level: 'L1',
    dimension: 'intelligence',
    text: '如果给你一堆零件和材料，你最想做什么？',
    theorySource: 'Gardner MI',
    options: [
      { id: 'L1-ABILITY-003-A', text: '照着说明书完美组装', scores: [{ dimension: 'intelligence', subDimension: 'intel.logicMath', value: 3 }] },
      { id: 'L1-ABILITY-003-B', text: '不看说明书，自己瞎拼出个新东西', scores: [{ dimension: 'intelligence', subDimension: 'intel.spatial', value: 3 }] },
      { id: 'L1-ABILITY-003-C', text: '拆开研究每个零件是干什么的', scores: [{ dimension: 'intelligence', subDimension: 'intel.naturalist', value: 3 }] },
      { id: 'L1-ABILITY-003-D', text: '和别人一起合作拼', scores: [{ dimension: 'intelligence', subDimension: 'intel.interpersonal', value: 3 }] },
    ],
  },
  {
    id: 'L1-ABILITY-004',
    type: 'binary',
    level: 'L1',
    dimension: 'intelligence',
    text: '你更容易注意到什么？',
    theorySource: 'Gardner MI',
    options: [
      { id: 'L1-ABILITY-004-A', text: '别人说话时的语气和表情变化', scores: [{ dimension: 'intelligence', subDimension: 'intel.interpersonal', value: 2 }] },
      { id: 'L1-ABILITY-004-B', text: '周围环境的细节（颜色搭配、声音、气味）', scores: [{ dimension: 'intelligence', subDimension: 'intel.naturalist', value: 1 }, { dimension: 'intelligence', subDimension: 'intel.spatial', value: 1 }] },
    ],
  },
  {
    id: 'L1-ABILITY-005',
    type: 'scenario',
    level: 'L1',
    dimension: 'intelligence',
    text: '老师让全班解一道很难的题，你的反应是？',
    theorySource: 'Gardner MI',
    options: [
      { id: 'L1-ABILITY-005-A', text: '兴奋！越难越想挑战', scores: [{ dimension: 'intelligence', subDimension: 'intel.logicMath', value: 3 }] },
      { id: 'L1-ABILITY-005-B', text: '先看看有没有人一起讨论', scores: [{ dimension: 'intelligence', subDimension: 'intel.interpersonal', value: 3 }] },
      { id: 'L1-ABILITY-005-C', text: '试着用画图或者摆东西来帮助理解', scores: [{ dimension: 'intelligence', subDimension: 'intel.spatial', value: 2 }, { dimension: 'intelligence', subDimension: 'intel.bodily', value: 1 }] },
      { id: 'L1-ABILITY-005-D', text: '心里想"为什么要学这个"，有点烦', scores: [{ dimension: 'intelligence', subDimension: 'intel.intrapersonal', value: 3 }] },
    ],
  },
  {
    id: 'L1-ABILITY-006',
    type: 'binary',
    level: 'L1',
    dimension: 'intelligence',
    text: '同学们都说你：',
    theorySource: 'Gardner MI',
    options: [
      { id: 'L1-ABILITY-006-A', text: '嘴巴厉害（会讲故事/会辩论/会逗人笑）', scores: [{ dimension: 'intelligence', subDimension: 'intel.linguistic', value: 2 }] },
      { id: 'L1-ABILITY-006-B', text: '手巧（会画画/会做手工/运动好）', scores: [{ dimension: 'intelligence', subDimension: 'intel.bodily', value: 1 }, { dimension: 'intelligence', subDimension: 'intel.spatial', value: 1 }] },
    ],
  },
  {
    id: 'L1-ABILITY-007',
    type: 'scenario',
    level: 'L1',
    dimension: 'intelligence',
    text: '音乐课上，你最享受的部分是？',
    theorySource: 'Gardner MI - Musical',
    options: [
      { id: 'L1-ABILITY-007-A', text: '唱歌或者演奏乐器', scores: [{ dimension: 'intelligence', subDimension: 'intel.musical', value: 3 }] },
      { id: 'L1-ABILITY-007-B', text: '听老师讲音乐背后的故事', scores: [{ dimension: 'intelligence', subDimension: 'intel.linguistic', value: 3 }] },
      { id: 'L1-ABILITY-007-C', text: '跟着节奏拍手或跳舞', scores: [{ dimension: 'intelligence', subDimension: 'intel.bodily', value: 3 }] },
      { id: 'L1-ABILITY-007-D', text: '其实我对音乐课没什么感觉', scores: [] },
    ],
  },
  {
    id: 'L1-ABILITY-008',
    type: 'binary',
    level: 'L1',
    dimension: 'intelligence',
    text: '你路过一个从没走过的小巷子，你会？',
    theorySource: 'Gardner MI - Naturalist + Jung N',
    options: [
      { id: 'L1-ABILITY-008-A', text: '很想进去看看里面有什么', scores: [{ dimension: 'intelligence', subDimension: 'intel.naturalist', value: 2 }] },
      { id: 'L1-ABILITY-008-B', text: '还是走熟悉的路吧', scores: [{ dimension: 'energy', subDimension: 'energy.certainty', value: 2 }] },
    ],
  },

  // ============ RIASEC 兴趣图谱 (8题) ============
  {
    id: 'L1-RIASEC-001',
    type: 'ranking',
    level: 'L1',
    dimension: 'riasec',
    text: '如果可以加入一个超酷的课外小组，你最想去哪个？给它们排个顺序（1=最想，4=最不想）：',
    theorySource: 'Holland RIASEC',
    options: [
      { id: 'L1-RIASEC-001-A', text: '科学实验小组（做实验、拆东西、研究为什么）', scores: [{ dimension: 'riasec', subDimension: 'riasec.I', value: 0 }] },
      { id: 'L1-RIASEC-001-B', text: '戏剧/绘画/音乐小组（创作和表演）', scores: [{ dimension: 'riasec', subDimension: 'riasec.A', value: 0 }] },
      { id: 'L1-RIASEC-001-C', text: '志愿者/心理小组（帮助别人、倾听别人的故事）', scores: [{ dimension: 'riasec', subDimension: 'riasec.S', value: 0 }] },
      { id: 'L1-RIASEC-001-D', text: '商业/辩论小组（模拟做老板、打比赛）', scores: [{ dimension: 'riasec', subDimension: 'riasec.E', value: 0 }] },
    ],
  },
  {
    id: 'L1-RIASEC-002',
    type: 'scenario',
    level: 'L1',
    dimension: 'riasec',
    text: '你在B站/YouTube上最爱看什么类型的视频？',
    theorySource: 'Holland RIASEC',
    options: [
      { id: 'L1-RIASEC-002-A', text: '科普/解密/冷知识（"十万个为什么"类）', scores: [{ dimension: 'riasec', subDimension: 'riasec.I', value: 3 }] },
      { id: 'L1-RIASEC-002-B', text: '手工/绘画/创意制作', scores: [{ dimension: 'riasec', subDimension: 'riasec.A', value: 2 }, { dimension: 'riasec', subDimension: 'riasec.R', value: 1 }] },
      { id: 'L1-RIASEC-002-C', text: '搞笑/vlog/日常分享', scores: [{ dimension: 'riasec', subDimension: 'riasec.S', value: 3 }] },
      { id: 'L1-RIASEC-002-D', text: '游戏攻略/策略分析', scores: [{ dimension: 'riasec', subDimension: 'riasec.I', value: 2 }, { dimension: 'riasec', subDimension: 'riasec.E', value: 1 }] },
    ],
  },
  {
    id: 'L1-RIASEC-003',
    type: 'binary',
    level: 'L1',
    dimension: 'riasec',
    text: '你更喜欢哪种游戏？',
    theorySource: 'Holland RIASEC',
    options: [
      { id: 'L1-RIASEC-003-A', text: '需要动脑筋的（棋类、解谜、策略游戏）', scores: [{ dimension: 'riasec', subDimension: 'riasec.I', value: 2 }] },
      { id: 'L1-RIASEC-003-B', text: '需要动手和反应快的（运动、动作游戏、搭建）', scores: [{ dimension: 'riasec', subDimension: 'riasec.R', value: 2 }] },
    ],
  },
  {
    id: 'L1-RIASEC-004',
    type: 'scenario',
    level: 'L1',
    dimension: 'riasec',
    text: '如果你是班长，你最想做什么？',
    theorySource: 'Holland RIASEC',
    options: [
      { id: 'L1-RIASEC-004-A', text: '组织一场超好玩的班级活动', scores: [{ dimension: 'riasec', subDimension: 'riasec.E', value: 3 }] },
      { id: 'L1-RIASEC-004-B', text: '帮班里有困难的同学', scores: [{ dimension: 'riasec', subDimension: 'riasec.S', value: 3 }] },
      { id: 'L1-RIASEC-004-C', text: '把班级卫生、纪律管得井井有条', scores: [{ dimension: 'riasec', subDimension: 'riasec.C', value: 3 }] },
      { id: 'L1-RIASEC-004-D', text: '其实我不太想当班长', scores: [{ dimension: 'riasec', subDimension: 'riasec.I', value: 2 }, { dimension: 'riasec', subDimension: 'riasec.A', value: 1 }] },
    ],
  },
  {
    id: 'L1-RIASEC-005',
    type: 'binary',
    level: 'L1',
    dimension: 'riasec',
    text: '写作文的时候，你更擅长：',
    theorySource: 'Holland RIASEC',
    options: [
      { id: 'L1-RIASEC-005-A', text: '编故事、写想象作文', scores: [{ dimension: 'riasec', subDimension: 'riasec.A', value: 2 }] },
      { id: 'L1-RIASEC-005-B', text: '写观察日记、说明文', scores: [{ dimension: 'riasec', subDimension: 'riasec.I', value: 1 }, { dimension: 'riasec', subDimension: 'riasec.C', value: 1 }] },
    ],
  },
  {
    id: 'L1-RIASEC-006',
    type: 'scenario',
    level: 'L1',
    dimension: 'riasec',
    text: '如果你有一个超能力，你最想要哪个？',
    theorySource: 'Holland RIASEC',
    options: [
      { id: 'L1-RIASEC-006-A', text: '能瞬间学会任何乐器或画出任何东西', scores: [{ dimension: 'riasec', subDimension: 'riasec.A', value: 3 }] },
      { id: 'L1-RIASEC-006-B', text: '能看到任何东西的内部结构（原子、机器、身体）', scores: [{ dimension: 'riasec', subDimension: 'riasec.I', value: 3 }] },
      { id: 'L1-RIASEC-006-C', text: '能听懂所有人心里在想什么', scores: [{ dimension: 'riasec', subDimension: 'riasec.S', value: 3 }] },
      { id: 'L1-RIASEC-006-D', text: '能让所有人都听你的话', scores: [{ dimension: 'riasec', subDimension: 'riasec.E', value: 3 }] },
    ],
  },
  {
    id: 'L1-RIASEC-007',
    type: 'binary',
    level: 'L1',
    dimension: 'riasec',
    text: '你更羡慕谁？',
    theorySource: 'Holland RIASEC',
    options: [
      { id: 'L1-RIASEC-007-A', text: '发明了很酷东西的科学家/工程师', scores: [{ dimension: 'riasec', subDimension: 'riasec.I', value: 1 }, { dimension: 'riasec', subDimension: 'riasec.R', value: 1 }] },
      { id: 'L1-RIASEC-007-B', text: '很多人喜欢的歌手/作家/导演', scores: [{ dimension: 'riasec', subDimension: 'riasec.A', value: 2 }] },
    ],
  },
  {
    id: 'L1-RIASEC-008',
    type: 'scenario',
    level: 'L1',
    dimension: 'riasec',
    text: '考试结束后，你通常会：',
    theorySource: 'Holland RIASEC + Jung',
    options: [
      { id: 'L1-RIASEC-008-A', text: '赶紧对答案，想知道对了多少', scores: [{ dimension: 'riasec', subDimension: 'riasec.C', value: 3 }] },
      { id: 'L1-RIASEC-008-B', text: '不太在意分数，开始想考完可以去玩什么', scores: [{ dimension: 'drive', subDimension: 'drive.freedom', value: 3 }] },
      { id: 'L1-RIASEC-008-C', text: '和同学讨论哪道题有意思', scores: [{ dimension: 'riasec', subDimension: 'riasec.I', value: 2 }, { dimension: 'riasec', subDimension: 'riasec.S', value: 1 }] },
      { id: 'L1-RIASEC-008-D', text: '反思哪里没做好，下次怎么改进', scores: [{ dimension: 'intelligence', subDimension: 'intel.intrapersonal', value: 3 }] },
    ],
  },

  // ============ 核心驱动力 (4题) ============
  {
    id: 'L1-DRIVE-001',
    type: 'ranking',
    level: 'L1',
    dimension: 'drive',
    text: '长大后，你觉得下面哪个最重要？排个顺序（1=最重要）：',
    theorySource: 'Schein Career Anchors',
    options: [
      { id: 'L1-DRIVE-001-A', text: '做出一个很酷的作品（游戏/书/建筑/产品）', scores: [{ dimension: 'drive', subDimension: 'drive.creation', value: 0 }] },
      { id: 'L1-DRIVE-001-B', text: '搞明白世界上还没人搞明白的事', scores: [{ dimension: 'drive', subDimension: 'drive.explore', value: 0 }] },
      { id: 'L1-DRIVE-001-C', text: '帮到很多人，被需要', scores: [{ dimension: 'drive', subDimension: 'drive.connect', value: 0 }] },
      { id: 'L1-DRIVE-001-D', text: '成为很厉害的人，很多人认识你', scores: [{ dimension: 'drive', subDimension: 'drive.influence', value: 0 }] },
    ],
  },
  {
    id: 'L1-DRIVE-002',
    type: 'binary',
    level: 'L1',
    dimension: 'drive',
    text: '你更想要哪种生活？',
    theorySource: 'SDT + Schein AU/SE',
    options: [
      { id: 'L1-DRIVE-002-A', text: '每天都不一样，充满新鲜事', scores: [{ dimension: 'drive', subDimension: 'drive.freedom', value: 1 }, { dimension: 'drive', subDimension: 'drive.explore', value: 1 }] },
      { id: 'L1-DRIVE-002-B', text: '有规律、可预期，知道接下来会发生什么', scores: [{ dimension: 'drive', subDimension: 'drive.security', value: 2 }] },
    ],
  },
  {
    id: 'L1-DRIVE-003',
    type: 'scenario',
    level: 'L1',
    dimension: 'drive',
    text: '如果你做了一件很棒的事，你最开心的是：',
    theorySource: 'SDT + Schein',
    options: [
      { id: 'L1-DRIVE-003-A', text: '这件事本身很酷，我创造了它', scores: [{ dimension: 'drive', subDimension: 'drive.creation', value: 3 }] },
      { id: 'L1-DRIVE-003-B', text: '很多人看到了，给我点赞', scores: [{ dimension: 'drive', subDimension: 'drive.influence', value: 3 }] },
      { id: 'L1-DRIVE-003-C', text: '帮到了某个具体的人', scores: [{ dimension: 'drive', subDimension: 'drive.connect', value: 3 }] },
      { id: 'L1-DRIVE-003-D', text: '过程中我学到了很多新东西', scores: [{ dimension: 'drive', subDimension: 'drive.explore', value: 3 }] },
    ],
  },
  {
    id: 'L1-DRIVE-004',
    type: 'binary',
    level: 'L1',
    dimension: 'drive',
    text: '如果一件事做了没人知道，你还会做吗？',
    theorySource: 'SDT Intrinsic/Extrinsic',
    options: [
      { id: 'L1-DRIVE-004-A', text: '当然，我是为自己做的', scores: [{ dimension: 'drive', subDimension: 'drive.internal', value: 2 }] },
      { id: 'L1-DRIVE-004-B', text: '可能就没那么有动力了', scores: [{ dimension: 'drive', subDimension: 'drive.external', value: 2 }] },
    ],
  },

  // ============ 认知与决策风格 / 荣格 (6题) ============
  {
    id: 'L1-JUNG-001',
    type: 'binary',
    level: 'L1',
    dimension: 'cognitive',
    text: '老师讲了一个新知识，你更在意：',
    theorySource: 'Jung S-N',
    options: [
      { id: 'L1-JUNG-001-A', text: '记住具体的事实和步骤（比如公式怎么用、步骤是什么）', scores: [{ dimension: 'cognitive', subDimension: 'jung.S', value: 2 }] },
      { id: 'L1-JUNG-001-B', text: '搞懂为什么是这样，这个知识还能用在哪', scores: [{ dimension: 'cognitive', subDimension: 'jung.N', value: 2 }] },
    ],
  },
  {
    id: 'L1-JUNG-002',
    type: 'scenario',
    level: 'L1',
    dimension: 'cognitive',
    text: '写作文的时候，你更容易写出什么样的内容？',
    theorySource: 'Jung S-N',
    options: [
      { id: 'L1-JUNG-002-A', text: '观察到的真实细节——颜色、声音、味道、发生了什么', scores: [{ dimension: 'cognitive', subDimension: 'jung.S', value: 3 }] },
      { id: 'L1-JUNG-002-B', text: '自己脑子里冒出来的故事和想法——如果这样会怎样？', scores: [{ dimension: 'cognitive', subDimension: 'jung.N', value: 3 }] },
      { id: 'L1-JUNG-002-C', text: '两种都有，看心情', scores: [{ dimension: 'cognitive', subDimension: 'jung.S', value: 1 }, { dimension: 'cognitive', subDimension: 'jung.N', value: 1 }] },
      { id: 'L1-JUNG-002-D', text: '其实我不太喜欢写作文', scores: [] },
    ],
  },
  {
    id: 'L1-JUNG-003',
    type: 'binary',
    level: 'L1',
    dimension: 'cognitive',
    text: '两个好朋友吵架了都来找你，你会：',
    theorySource: 'Jung T-F',
    options: [
      { id: 'L1-JUNG-003-A', text: '分析谁的理由更有道理，帮他们讲道理', scores: [{ dimension: 'cognitive', subDimension: 'jung.T', value: 2 }] },
      { id: 'L1-JUNG-003-B', text: '先安慰他们的情绪，让他们都觉得被理解', scores: [{ dimension: 'cognitive', subDimension: 'jung.F', value: 2 }] },
    ],
  },
  {
    id: 'L1-JUNG-004',
    type: 'binary',
    level: 'L1',
    dimension: 'cognitive',
    text: '看动画片的时候，你更关注：',
    theorySource: 'Jung T-F',
    options: [
      { id: 'L1-JUNG-004-A', text: '剧情的逻辑——"这不合理啊！""为什么他要这样做？"', scores: [{ dimension: 'cognitive', subDimension: 'jung.T', value: 2 }] },
      { id: 'L1-JUNG-004-B', text: '角色的感受——"他好可怜""我好喜欢这个角色"', scores: [{ dimension: 'cognitive', subDimension: 'jung.F', value: 2 }] },
    ],
  },
  {
    id: 'L1-JUNG-005',
    type: 'binary',
    level: 'L1',
    dimension: 'cognitive',
    text: '出去旅游，你更喜欢：',
    theorySource: 'Jung J-P',
    options: [
      { id: 'L1-JUNG-005-A', text: '提前把每天要去哪里、吃什么都安排好', scores: [{ dimension: 'cognitive', subDimension: 'jung.J', value: 2 }] },
      { id: 'L1-JUNG-005-B', text: '到了再说，想去哪去哪，随便逛', scores: [{ dimension: 'cognitive', subDimension: 'jung.P', value: 2 }] },
    ],
  },
  {
    id: 'L1-JUNG-006',
    type: 'binary',
    level: 'L1',
    dimension: 'cognitive',
    text: '做作业的时候，你通常：',
    theorySource: 'Jung J-P',
    validationPairId: 'L1-JUNG-005',
    options: [
      { id: 'L1-JUNG-006-A', text: '先做完再玩，做完心里才踏实', scores: [{ dimension: 'cognitive', subDimension: 'jung.J', value: 2 }] },
      { id: 'L1-JUNG-006-B', text: '先玩一会，截止前再赶——反正总能做完', scores: [{ dimension: 'cognitive', subDimension: 'jung.P', value: 2 }] },
    ],
  },
];

export const L1QuestionBank: QuestionBank = {
  level: 'L1',
  questions,
  estimatedMinutes: 10,
};
